name: CICD-SSH
on:
  push:
      branches: [ main ]
      paths:
        - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }} 
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: 22
        script: cd nextjs-dashboard
    - name: git pull
      run: |
        pwd
        # cd ${{ github.event.repository.name }}
        git pull origin master
    - name: npm install & build
      run: |
        npm install
        npm run build
    - name: kill next-server
      run: |
        killall -9 next-server
    - name: npm start
      run: |
        npm run start
