name: CICD-SSH
on:
  push:
      branches: [ "main", "master" ]
      paths:
        - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }} 
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: 22
        script: |
          cd ${{ github.event.repository.name }}
          pwd
          git pull origin master
          echo "git pull complete"
          npm install
          echo "npm install complete"
          npm run build
          echo "npm build complete"
          pm2 startOrRestart pm2.config.js --env prod
          echo "pm2 restart complete"
          
      
