name: CICD-SSH
on:
  push:
      branches: [ main ]
      paths:
        - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }} 
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: 22
        script: |
          cd ${{ github.event.repository.name }}
          pwd
          git pull origin master
          echo "git pull complete"
          npm install
          echo "npm install complete"
          npm run build
          echo "npm build complete"
          pm2 delete next-app 2> /dev/null || pm2 start "npm run start" --name "next-app"
          echo "pm2 delete & npm start"
          sudo systemctl restart nginx
          echo "nginx restart"
