name: CICD-SSH
on:
  push:
      branches: [ main ]
      paths:
        - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }} 
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: 22
        run: |
          cd ${{ github.event.repository.name }}
    - name: git pull
      run: 
        git pull origin master
    - name: npm install & build & start
        npm install
        npm run build
        killall -9 next-server
        npm run start
